import { Inter, Poppins } from 'next/font/google';
import { Metadata, Viewport } from 'next';

import SolanaWalletProvider from '@/context/SolanaWalletProvider';
import QueryProvider from '@/context/QueryProvider';

import NavBar from '@/components/layout/nav-bar';
import Footer from '@/components/layout/footer';
import { Toaster } from '@/components/ui/toaster';
import WelcomeModal from '@/components/layout/welcome-modal';

import '@solana/wallet-adapter-react-ui/styles.css';
import './globals.css';

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
});

const poppins = Poppins({
    variable: '--font-poppins',
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export const viewport: Viewport = {
    initialScale: 1,
    width: 'device-width',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' className='dark'>
            <QueryProvider>
                <SolanaWalletProvider>
                    <body
                        className={`${inter.variable} ${poppins.variable} font-body antialiased min-h-screen flex flex-col bg-background text-foreground relative`}
                    >
                        <NavBar />
                        <main className='flex-grow container mx-auto px-4 py-6 sm:py-8 z-10'>
                            {children}
                        </main>
                        <Toaster />
                        <Footer />
                    </body>
                    <WelcomeModal />
                </SolanaWalletProvider>
            </QueryProvider>
        </html>
    );
}
